### ISSUE TITLE
Check faucet transfer request interval

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/dusty-faucet#5]
https://github.com/PlasmNetwork/dusty-faucet/blob/d86764b112bbd7649e569d9734a456bcac6fc6b6/contract/lib.rs#L56

Can you add a hash map like `StorageHashMap<AccountId, BlockNumber>` or `StorageHashMap<AccountId, u64>` to track the latest block number of when an account has received the funds? And send funds only if the last block number mapped to `to: AccountId` + `DRIP_THRESHOLD` < `Self::env().block_number()`. The threshold should be long enough so that any account can only request tokens once per hour

**Comment by VadneyK** [comment]
can I use utc::now() instead of blocktime? It's hard to test the block times and apparently the miners can arbitrarily set block times (although having malicious miners is probably rare) also the amount of time to wait may change as the speed at which we get the blocks may change too so looking at the global clock would be more relaible. Added this feature, just need to refactor

**Comment by VadneyK** [comment]
https://github.com/PlasmNetwork/dusty-faucet/commit/777c2ac8fe62e9d0d901eec43ce306da1e786a9e
